#pragma once

#define BAMBU_MONITOR_APP_NAME "Bambu Fleet"

#define BAMBU_MONITOR_STATUS_TEXT_SIZE 64U
#define BAMBU_MONITOR_DETAIL_TEXT_SIZE 96U
#define BAMBU_MONITOR_WIFI_ENTRY_SIZE 48U
#define BAMBU_MONITOR_MAX_WIFI_NETWORKS 16U
#define BAMBU_MONITOR_MAX_PRINTERS 8U
#define BAMBU_MONITOR_SERIAL_SIZE 32U
#define BAMBU_MONITOR_NAME_SIZE 48U
#define BAMBU_MONITOR_MODEL_SIZE 24U
#define BAMBU_MONITOR_IP_SIZE 16U
#define BAMBU_MONITOR_ACCESS_CODE_SIZE 32U
#define BAMBU_MONITOR_FILE_SIZE 48U
#define BAMBU_MONITOR_WIFI_SIGNAL_SIZE 16U
#define BAMBU_MONITOR_MENU_VISIBLE_ITEMS 5U
