#pragma once

#include <storage/storage.h>

#define BAMBU_MONITOR_APP_NAME "Bambu Fleet"

#define BAMBU_MONITOR_STATUS_TEXT_SIZE 64U
#define BAMBU_MONITOR_DETAIL_TEXT_SIZE 192U
#define BAMBU_MONITOR_WIFI_ENTRY_SIZE 48U
#define BAMBU_MONITOR_MAX_WIFI_NETWORKS 16U
#define BAMBU_MONITOR_MAX_PRINTERS 8U
#define BAMBU_MONITOR_SERIAL_SIZE 32U
#define BAMBU_MONITOR_NAME_SIZE 48U
#define BAMBU_MONITOR_MODEL_SIZE 24U
#define BAMBU_MONITOR_IP_SIZE 16U
#define BAMBU_MONITOR_ACCESS_CODE_SIZE 32U
#define BAMBU_MONITOR_FILE_SIZE 48U
#define BAMBU_MONITOR_WIFI_SIGNAL_SIZE 16U
#define BAMBU_MONITOR_MENU_VISIBLE_ITEMS 4U
#define BAMBU_MONITOR_PASSWORD_SIZE 64U
#define BAMBU_MONITOR_WIFI_SSID_SIZE 34U
#define BAMBU_MONITOR_TOKEN_SIZE 192U
#define BAMBU_MONITOR_SD_ASSET_ROOT STORAGE_EXT_PATH_PREFIX "/apps_assets"
#define BAMBU_MONITOR_SD_ASSET_DIR STORAGE_EXT_PATH_PREFIX "/apps_assets/bambu_fleet"
#define BAMBU_MONITOR_SD_TOKEN_PATH BAMBU_MONITOR_SD_ASSET_DIR "/bambu_token.txt"
#define BAMBU_MONITOR_SD_PRINTER_CACHE_PATH BAMBU_MONITOR_SD_ASSET_DIR "/found_printers.json"
#define BAMBU_MONITOR_SD_LOG_PATH BAMBU_MONITOR_SD_ASSET_DIR "/bambu_fleet.log"
#define BAMBU_MONITOR_SD_SETTINGS_PATH BAMBU_MONITOR_SD_ASSET_DIR "/bambu_fleet.cfg"
#define BAMBU_MONITOR_DETAIL_REFRESH_MS 3000U
#define BAMBU_MONITOR_DETAIL_REFRESH_IDLE_MS 1200U
